-- Run this in Supabase SQL Editor

-- 1. Create Tables
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE products (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  barcode TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category_id BIGINT NOT NULL REFERENCES categories(id),
  photo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE product_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 10),
  price DECIMAL(10,2) NOT NULL,
  notes TEXT,
  record_date TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (Security best practice)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies (Allow public access for this demo app)
-- In a real app with users, you would check "auth.uid() = user_id"
CREATE POLICY "Public products access" ON products FOR ALL USING (true);
CREATE POLICY "Public records access" ON product_records FOR ALL USING (true);
CREATE POLICY "Public categories access" ON categories FOR ALL USING (true);

-- 4. Seed Data
INSERT INTO categories (name, icon) VALUES 
('Dairy', '🥛'),
('Meat & Sausage', '🥩'),
('Fish & Seafood', '🐟'),
('Bread & Bakery', '🍞'),
('Fruits & Vegetables', '🥗'),
('Grains & Pasta', '🌾'),
('Sweets & Snacks', '🍫'),
('Drinks', '🥤'),
('Ready Meals', '🍱');
